### ISSUE TITLE
CORS problem in login page

### ISSUE THREAD

**Issue by shehza-d** [RuhamaMalik/summit_devathon_1#1]
![image](https://github.com/RuhamaMalik/summit_devathon_1/assets/93990677/e5116a6c-f68e-4778-b7c4-fd2e86a3eb7f)

**Comment by RuhamaMalik** [comment]
It's working fine in my system.... close the app and try to login again
after refresh.... make sure your internet connected successfully. Inshallah
it will be logged. But if it still doesn't work let me know.

**Comment by shehza-d** [comment]
Yes it's working but show errors in UI 
(i accidentally tried logging in before signing up)

**Comment by RuhamaMalik** [comment]
Glad to know the code is working fine.🎉
no worries! It happens to the best of us. It's like putting on your shoes
before your socks. 😄 Feel free to contact me if you have any questions or
problems.👍
